	public void testErrorAssert() throws InterruptedException {
        Category log = ThreadCategory.getInstance();
        log.info("An Info message");
        log.warn("A warn message");

		try {
			MockLogAppender.assertNotGreaterOrEqual(Level.ERROR);
		} catch (AssertionFailedError e) {
			fail("Received unexpected AssertionFailedError: " + e);
		}
	}

