    @Test
    public void testServerFailed() throws Exception {
        m_request.m_reqID = 24212;
        try {
            m_request.verifyResponse(servFailResponseBytes, servFailResponseBytes.length);            
        } catch (IOException ioe) {
            assertEquals("Server Failure (2)", ioe.getMessage());
            return;
        }
        throw new Exception("Should have caught an IOException for ServFail!");
    }

