	public void testErrorAssert() throws InterruptedException {
		LogUtils.infof(this, "An Info message");
		LogUtils.warnf(this, "A warn message");

		try {
			MockLogAppender.assertNotGreaterOrEqual(Level.ERROR);
		} catch (final AssertionFailedError e) {
			fail("Received unexpected AssertionFailedError: " + e);
		}
	}

